feat: add unit tests for components using AI tools
KasperskyLab/uif pull request #66
Opened 2024-06-21 18:57 UTC by bloomou

2024-06-21 18:57 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/KasperskyLab/uif?pullRequest=66) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/KasperskyLab/uif?pullRequest=66) before we can accept your contribution.<br/><hr/>**Ani Sarkisyan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/KasperskyLab/uif?pullRequest=66) it.</sub>

2024-06-26 13:37 UTC, yasevplaton approved these changes

2024-06-26 14:47 UTC, neafanasev requested changes

2024-06-26 14:47 UTC, neafanasev commented on packages/kaspersky-components/src/search/__tests__/search.test.tsx
> +      <ConfigProvider theme={ThemeKey.Light} locale="en-us">
зачем тут накидывается конфиг провайдер?

2024-06-26 14:47 UTC, neafanasev commented on packages/kaspersky-components/src/sidebar/__tests__/Sidebar.test.tsx
> +  it('should handle rapid visibility toggling without errors', () => {
странный тест, мы тут каждый раз просто рендерим новый компонент, неясно что проверяется. было бы отлично, если бы меняли какой то стейт, который отвечает за visible в компоненте

2024-06-26 14:47 UTC, neafanasev commented on packages/kaspersky-components/src/tree-select/__tests__/TreeSelect.test.tsx
> +  it('should handle undefined treeCheckable prop', () => {
тут чет какая то шляпа со всеми тестами до конца файла. по сути, если мы отрендерим просто  <TreeSelect />, то все проверяемые тут пропы будут undefined. неясно зачем крутить тут 5 тестов. тем более, что мы проверяем не наличие treeselect в коде, а контейнер - expect(container).toBeInTheDocument()

2024-06-27 16:56 UTC, bloomou commented on packages/kaspersky-components/src/tree-select/__tests__/TreeSelect.test.tsx
> +  it('should handle undefined treeCheckable prop', () => {
исправлено

2024-06-27 16:58 UTC, bloomou commented on packages/kaspersky-components/src/sidebar/__tests__/Sidebar.test.tsx
> +  it('should handle rapid visibility toggling without errors', () => {
состояния в среде тестирования обновляются чуть другим образом, тест не выполняет перерендеринг компонента после изменения состояния, поэтому рекомендуется использовать rerender

2024-06-27 16:59 UTC, bloomou commented on packages/kaspersky-components/src/search/__tests__/search.test.tsx
> +      <ConfigProvider theme={ThemeKey.Light} locale="en-us">
исправлено

2024-06-27 16:59 UTC, bloomou commented on packages/kaspersky-components/src/modal/__tests__/modal.test.tsx
> +    await waitFor(() => expect(baseElement.querySelector(`[data-testid="${testId}"]`)).toBeInTheDocument())
исправлено

2024-06-27 16:59 UTC, bloomou commented on packages/kaspersky-components/src/label/__tests__/Label.test.tsx
> +
мне кажется, что из-за того, что компонент используется, можно оставить тесты, хоть компонент и не будет дорабатываться

2024-06-27 17:00 UTC, bloomou commented on packages/kaspersky-components/src/anchor-links/__tests__/Anchor.test.tsx
> +    const items = [
исправлено

2024-06-27 17:00 UTC, bloomou commented on packages/kaspersky-components/src/accordion/__tests__/Accordion.test.tsx
> +  test('accordion panel with custom title size should render', () => {
исправлено

2024-06-27 17:00 UTC, bloomou commented on packages/kaspersky-components/src/accordion/__tests__/Accordion.test.tsx
> +    const handleClick = jest.fn()
исправлено

2024-06-28 09:43 UTC, neafanasev commented on packages/kaspersky-components/src/label/__tests__/Label.test.tsx
> +
тесты нам помогают отлавливать ошибки. в в6 мы его исправлять не будем, тк если кто то придет с предложением исправления, то мы его отправим переезжать на филд. если он используется и к нам никто не приходит - значит работает штатно. юнит-тесты все таки в первую очередь нужны для того, чтобы отследить регрессию при изменений, а изменений тут не будет. просто так лишние тесты будут гоняться

2024-06-28 09:48 UTC, neafanasev approved these changes

2024-06-28 10:37 UTC, vostrik commented on packages/kaspersky-components/src/label/__tests__/Label.test.tsx
> +
Обсудили голосом, договорились:

1. текущие тесты заливаем;
2. прорабатываем подмену реализации на Field и отметку deprecated для Label.

2024-07-01 08:22 UTC, merged